name: Azure Container Apps Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build_container_images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Build Backend API Container Image
        run: |
          az acr build --registry ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }} --image ${{ vars.BACKEND_API_NAME }}:${{ github.sha }} ./TasksTracker.TasksManager.Backend.Api
      - name: Build Frontend WebApp Container Image
        run: |
          az acr build --registry ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }} --image ${{ vars.FRONTEND_WEBAPP_NAME }}:${{ github.sha }} ./TasksTracker.WebPortal.Frontend.Ui
      - name: Build Backend Service Container Image
        run: |
          az acr build --registry ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }} --image ${{ vars.BACKEND_SERVICE_NAME }}:${{ github.sha }} ./TasksTracker.Processor.Backend.Svc
  deploy_container_apps:
    runs-on: ubuntu-latest
    needs: build_container_images

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Build and deploy Backend API Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          imageToDeploy: ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ vars.BACKEND_SERVICE_NAME }}:${{ github.sha }}
          containerAppName: ${{ vars.BACKEND_CONTAINER_APP_NAME }}
          resourceGroup: ${{ vars.RESOURCE_GROUP }}
      - name: Build and deploy Frontend WebApp Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          imageToDeploy: ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ vars.FRONTEND_WEBAPP_NAME }}:${{ github.sha }}
          containerAppName: ${{ vars.FRONTEND_WEBAPP_NAME }}
          resourceGroup: ${{ vars.RESOURCE_GROUP }}
      - name: Build and deploy Backend Service Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          imageToDeploy: ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ vars.BACKEND_SERVICE_NAME }}:${{ github.sha }}
          containerAppName: ${{ vars.BACKEND_SERVICE_NAME }}
          resourceGroup: ${{ vars.RESOURCE_GROUP }}